/*
Title: <Game Name> Quit Button
Author: 
Translator: David Sarkies
Version: 1.0
Date: 8 December 2025
Source: 
*/

package controller;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;

import ui.GameController;

/**
 * A button action listener that quits or restarts the game when triggered.
 * <p>
 * When the user activates the button, this listener decides whether to
 * restart the game or close the UI entirely based on the {@code shouldRestart}
 * flag provided at construction time.
 * </p>
 */
public class QuitButton implements ActionListener {
	
    /** Reference to the main game controller for managing game lifecycle actions. */
	private final GameController controller;
	
    /**
     * Indicates whether the game should restart after the quit action.
     * If {@code true}, the game restarts; if {@code false}, the UI closes.
     */
	private final boolean shouldRestart;
	
    /**
     * Constructs a {@code QuitButton} listener.
     *
     * @param controller    the {@link GameController} responsible for handling
     *                      restart or shutdown operations; must not be {@code null}.
     * @param shouldRestart {@code true} to restart the game on quit,
     *                      {@code false} to simply close the UI.
     * @throws NullPointerException if {@code controller} is {@code null}.
     */
	public QuitButton(GameController controller,boolean shouldRestart) {
		this.controller = Objects.requireNonNull(controller,"GameController cannot be null");
		this.shouldRestart = shouldRestart;
	}
	
    /**
     * Invoked when the associated quit button is clicked.
     * <p>
     * Delegates to {@link #handleQuitAction()} to perform the
     * appropriate quit or restart operation.
     * </p>
     *
     * @param event the {@link ActionEvent} generated by the button click.
     */
	@Override
	public void actionPerformed(ActionEvent event) {
		handleQuitAction();
	}
	
    /**
     * Handles the quit action by either restarting the game or
     * closing the UI based on the {@link #shouldRestart} flag.
     * <p>
     * Any exceptions thrown during the process are caught and logged
     * at {@link java.util.logging.Level#SEVERE}.
     * </p>
     */
	private void handleQuitAction() {
	    try {
	        if (shouldRestart) {
	            controller.restart();
	        } else {
	            controller.closeUI();
	        }
	    } catch (Exception e) {
	        Logger.getLogger(QuitButton.class.getName())
	              .log(Level.SEVERE, "Quit action failed", e);
	    }
	}
}

/* 3 December 2025 - Created File
 * 8 December 2025 - Increased version number
 */
